/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/airplane/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const HELiX_SPEED = 6;

export function Airplane({ ...props }) {
  const { nodes, materials } = useGLTF('models/airplane/model.glb')
  const helixRef = useRef()

  useFrame((_state, delta) => {
    helixRef.current.rotation.x += delta * HELiX_SPEED
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry} >
        <meshStandardMaterial color="white" />
      </mesh>
      <mesh geometry={nodes.PUSHILIN_Plane_Helix.geometry} position={[1.09, 0.23, 0]} ref={helixRef}>
        <meshStandardMaterial color="white" />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/airplane/model.glb')
