/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/cloud/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud({ opacity, ...props }) {
  const { nodes, materials } = useGLTF('models/cloud/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry}>
        <meshStandardMaterial opacity={opacity} transparent envMapIntensity={2} />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/cloud/model.glb')
